export default [
  {
    name: 'Olivia Owner',
    role: 'Product Manager',
    email: 'owner@interviewly.test',
    telegram: '@olivia_owner',
    level: 'middle',
    stack: ['Product Strategy', 'Agile', 'Stakeholder Management', 'UX Research'],
    bio: 'Experienced product manager focused on building interview platforms. 7+ years in SaaS.',
  },
  {
    name: 'Ivan Interviewer',
    role: 'Senior Backend Engineer',
    email: 'interviewer@interviewly.test',
    telegram: '@ivan_dev',
    level: 'senior',
    stack: ['NestJS', 'PostgreSQL', 'Docker', 'Kubernetes', 'TypeScript', 'GraphQL'],
    bio: 'Passionate backend developer with expertise in scalable systems. 10+ years of experience.',
  },
  {
    name: 'Clara Candidate',
    role: 'Full Stack Developer',
    email: 'candidate@interviewly.test',
    telegram: '@clara_code',
    level: 'junior',
    stack: ['React', 'Node.js', 'MongoDB', 'JavaScript', 'CSS', 'REST API'],
    bio: 'Eager junior full stack developer with 1-2 years of experience. Always learning and improving.',
  },
  {
    name: 'Alice Admin',
    role: 'DevOps Engineer',
    email: 'admin@interviewly.test',
    telegram: '@alice_ops',
    level: 'senior',
    stack: ['Kubernetes', 'Docker', 'AWS', 'CI/CD', 'Terraform', 'Linux'],
    bio: 'DevOps specialist with 8+ years managing cloud infrastructure. Strong focus on automation.',
  },
  {
    name: 'Noah User',
    role: 'Frontend Developer',
    email: 'user@interviewly.test',
    telegram: '@noah_frontend',
    level: 'middle',
    stack: ['React', 'Vue.js', 'TypeScript', 'TailwindCSS', 'Webpack', 'Testing Library'],
    bio: 'Frontend enthusiast with 5 years of experience building beautiful and performant UIs.',
  },
];
