export default [
  {
    email: 'owner@interviewly.test',
    firstName: 'Olivia',
    lastName: 'Owner',
    timeZone: 'Europe/Moscow',
    registrationCompleted: true,
    emailVerifiedAt: new Date('2026-08-01T10:00:00.000Z'),
  },
  {
    email: 'interviewer@interviewly.test',
    firstName: 'Ivan',
    lastName: 'Interviewer',
    timeZone: 'Europe/Moscow',
    registrationCompleted: true,
    emailVerifiedAt: new Date('2026-08-02T10:00:00.000Z'),
  },
  {
    email: 'candidate@interviewly.test',
    firstName: 'Clara',
    lastName: 'Candidate',
    timeZone: 'Europe/Berlin',
    registrationCompleted: true,
    emailVerifiedAt: new Date('2026-08-03T10:00:00.000Z'),
  },
  {
    email: 'admin@interviewly.test',
    firstName: 'Alice',
    lastName: 'Admin',
    timeZone: 'Europe/Moscow',
    isAdmin: true,
    registrationCompleted: true,
    emailVerifiedAt: new Date('2026-08-04T10:00:00.000Z'),
  },
  {
    email: 'user@interviewly.test',
    firstName: 'Noah',
    lastName: 'User',
    timeZone: 'Europe/Berlin',
    isAdmin: false,
    registrationCompleted: true,
    emailVerifiedAt: new Date('2026-08-05T10:00:00.000Z'),
  },
];
