import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import favicon from "@shared/assets/favicon.ico";
import "@shared/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <link rel="icon" href={favicon.src} />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
